// Korean for every string the plugin shows; English is the key. Unit, sprite and doodad names come from the editor as they are.
// `tests/ko.test.ts` fails on a `t("…")` or `msg("…")` in the source with no entry here, and on an entry nothing uses.
export const KO: Record<string, string> = {
  " ({n} skipped: {why})": " ({n}개 건너뜀: {why})",
  "Doodads": "장식물",
  "Ellipse": "타원",
  "Erase {n, plural, one {# doodad} other {# doodads}}": "장식물 {n}개 지우기",
  "Erase {n, plural, one {# sprite} other {# sprites}}": "스프라이트 {n}개 지우기",
  "Erase {n, plural, one {# unit} other {# units}}": "유닛 {n}개 지우기",
  "Eraser": "지우개",
  "Fill": "채우기",
  "Fog of War": "전장의 안개",
  "Freehand": "자유 곡선",
  "Jitter": "흩뜨리기",
  "Line": "선",
  "Nothing to paint": "그릴 것이 없습니다",
  "Paint": "그리기",
  "Paint with a tool": "도구로 그리기",
  "Paint {tool}: {what}": "그리기 ({tool}): {what}",
  "Paint: erased {n}": "그리기: {n}개 지움",
  "Paint: no tool called \"{id}\"": "그리기: \"{id}\" 도구가 없습니다",
  "Paint: nothing under the eraser": "그리기: 지우개 아래에 아무것도 없습니다",
  "Paint: open a map first": "그리기: 먼저 맵을 여세요",
  "Paint: shape dropped": "그리기: 도형을 버렸습니다",
  "Paint: {tool}": "그리기: {tool}",
  "Paint: {tool} changed nothing — {n, plural, one {that tile already is} other {those # tiles already are}} {what}{notes}": "그리기: {tool} — 바뀐 것이 없습니다. 타일 {n}개가 이미 {what}입니다{notes}",
  "Paint: {tool} of {what}{skipped}{notes}": "그리기: {tool} — {what}{skipped}{notes}",
  "Paint: {what}": "그리기: {what}",
  "Paint…": "그리기…",
  "Players": "플레이어",
  "Polygon": "다각형",
  "Rectangle": "사각형",
  "Spacing": "간격",
  "Spray": "스프레이",
  "Sprites": "스프라이트",
  "Star": "별",
  "Terrain": "지형",
  "Text": "텍스트",
  "Units": "유닛",
  "Width": "굵기",
  "a random player": "무작위 플레이어",
  "auto: {n}": "자동: {n}",
  "clear fog": "안개 지우기",
  "click the corners, click the first one again to finish": "꼭짓점을 클릭하고, 첫 꼭짓점을 다시 클릭하면 끝납니다",
  "click where the text starts": "텍스트가 시작할 곳을 클릭",
  "cycle players 1–8": "플레이어 1–8 돌아가며",
  "drag a corner to the opposite corner": "한 모서리에서 맞은편 모서리로 드래그",
  "drag from one end to the other": "한쪽 끝에서 다른 쪽 끝으로 드래그",
  "drag from the centre outwards; the drag sets the size and turns it": "중심에서 바깥으로 드래그. 드래그로 크기와 방향을 정합니다",
  "drag over what to remove": "지울 것 위로 드래그",
  "drag the box the ellipse fits in": "타원이 들어갈 상자를 드래그",
  "drag to draw": "드래그해서 그리기",
  "drag to scatter": "드래그해서 흩뿌리기",
  "draws a box from its centre.": "키: 상자를 중심에서부터 그립니다.",
  "drops the shape in progress; again, or a right-click, leaves the tool. Every stroke is one undo step.": "키: 그리던 도형을 버립니다. 한 번 더 누르거나 오른쪽 클릭하면 도구를 끝냅니다. 한 번 그을 때마다 실행 취소 한 단계입니다.",
  "filled": "속 채움",
  "fog": "안개",
  "grid": "격자",
  "no map is open": "열린 맵이 없습니다",
  "off the map": "맵 바깥",
  "pick a doodad in the palette": "팔레트에서 장식물을 고르세요",
  "pick a tool": "도구를 고르세요",
  "placement checks refused them": "배치 검사에서 거부됨",
  "points": "꼭짓점",
  "polygon": "다각형",
  "random": "무작위",
  "skip ones the placement checks refuse": "배치 검사에서 거부되는 것은 건너뛰기",
  "squares a box, rounds an ellipse, snaps a line to 45°.": "키: 상자는 정사각형, 타원은 원으로 만들고 선은 45° 단위로 맞춥니다.",
  "staggered": "엇갈린 격자",
  "switch to the Terrain, Doodads, Units, Sprites or Fog of War layer": "지형, 장식물, 유닛, 스프라이트, 전장의 안개 레이어 중 하나로 바꾸세요",
  "terrain {n}": "지형 {n}",
  "the palette's player": "팔레트의 플레이어",
  "tile {n}": "타일 {n}",
  "tile {n} ({label})": "타일 {n} ({label})",
  "type here, then click the map": "여기에 입력한 뒤 맵을 클릭하세요",
  "what the {layer} palette has picked": "{layer} 팔레트에서 고른 것",
  "{mode} for every player": "{mode}: 모든 플레이어",
  "{mode} for nobody": "{mode}: 플레이어 없음",
  "{mode} for {n, plural, one {player {list}} other {players {list}}}": "{mode}: 플레이어 {list}",
  "{n, plural, one {# tile} other {# tiles}}": "타일 {n}개",
  "{n, plural, one {# tile} other {# tiles}} / pixel": "픽셀당 타일 {n}개",
  "{name} · Player {n}": "{name} · 플레이어 {n}",
  "{name} · Player {n} · flipped": "{name} · 플레이어 {n} · 뒤집힘",
  "{n} × {what}": "{what} × {n}",
};
